### ISSUE TITLE
Consider replacing `setup.py ultratest` and `setup.py manualtest` with tox

### ISSUE THREAD

**Issue by toolness** [cloud-gov/cg-django-uaa#32]
When I wrote the test suite for this project, I didn't know about [`tox`](https://tox.readthedocs.io/en/latest/), which does what `setup.py ultratest` does, only better, since it packages the package and installs it into a separate virtualenv--thereby obviating the need for the `setup.py manualtest` command--and also tests it using different versions of python.

**Comment by bengerman13** [comment]
fixed in #61
