### ISSUE TITLE
Test multiple python versions and Django versions in CircleCI

### ISSUE THREAD

**Issue by toolness** [cloud-gov/cg-django-uaa#40]
The old travis config we removed in 4cef103e8d47302836a4edaee139d784c341dc48 tested multiple versions of Python and Django with cg-django-uaa but in an effort to resolve #38 as quickly as possible, I migrated us to CircleCI *without* support for this.

It looks like we need to leverage CircleCI's [workflows](https://circleci.com/docs/2.0/workflows/) feature to accomplish this.

**Comment by bengerman13** [comment]
closing since we're not using circleci anymore
