### ISSUE TITLE
Breaking change with pyJWT 2.0.0

### ISSUE THREAD

**Issue by lbeaufort** [cloud-gov/cg-django-uaa#51]
Hi there!

It looks like there’s a breaking change in version 2.0.0 of the `PyJWT` package released today.

> Drop deprecation warnings ([#515](https://github.com/jpadilla/pyjwt/pull/515))
> https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.md#v200

When using version 2.0.0, our application using `cg-django-uaa` for authentication was receiving the error 
```
 jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
```

In summary, it seems that in `pyJWT` version 2.0.0 when using `decode()`, the `algorithms` parameter is required because the `verify_signature` default value is `True`. (Docs: https://pyjwt.readthedocs.io/en/stable/api.html?highlight=options#jwt.decode).  We were able address this by pinning the `pyJWT` version to 1.71.

How your package uses `decode`:
https://github.com/cloud-gov/cg-django-uaa/blob/5347d5ab7e565d4c4cab91af1eda73f9d82861c4/uaa_client/authentication.py#L158

Thanks in advance!

**Comment by ccostino** [comment]
Thank you for reporting, @lbeaufort!

I'm noting here that it looks like the CHANGELOG file changed, here's the direct link to the deprecation notice for the line in question: https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.rst#dropped-deprecated-verify-param-in-jwtdecode
