### ISSUE TITLE
Remove Read the Docs Community (readthedocs.org) access to this repo

### ISSUE THREAD

**Issue by wz-gsa** [cloud-gov/cg-django-uaa#78]
Cloud.gov should only host documents using authorized government locations. Remove documentation from Read the Docs Community (readthedocs.org)

## Notes

- Ensure updated documentation resides in this repo.
- Ensure documentation is removed from Read the Docs Community (readthedocs.org) to avoid confusion.
- Revoke access for Read the Docs Community **(readthedocs.org)** under third party access policy in cloud-gov settings

## Acceptance Criteria

- [x] Ensure updated documentation resides in this repo.
- [x] Ensure documentation is removed from Read the Docs Community (readthedocs.org) to avoid confusion.
- [x] Revoke access for Read the Docs Community **(readthedocs.org)** under third party access policy in cloud-gov settings

**Comment by markdboyd** [comment]
Deleted readthedocs documentation, as you can see: https://cg-django-uaa.readthedocs.io/en/main/index.html 

Revoked access for readthedocs in the GitHub org.
